Repository golagola2020/hango-raspberry-pi, pull requests merged in 2020-10, with the labels that each got.

#5 [rasp/refectoring] 라즈베리파이 코드 최적화 및 모듈화
  hardware/raspberry/Env.py
  hardware/raspberry/Http.py
  hardware/raspberry/Serial.py
  hardware/raspberry/Speak.py
  hardware/raspberry/raspberry.py
  hardware/raspberry/testing-files/request_gTTS.py
  hardware/raspberry/testing-files/tts.py
Labels: 기능 개선, 라즈베리파이

#6 [rasp/refectoring] 클래스 모듈들 별도 폴더로 이전
  hardware/raspberry/module/Env.py
  hardware/raspberry/module/Http.py
  hardware/raspberry/module/Serial.py
  hardware/raspberry/module/Speak.py
  hardware/raspberry/raspberry.py
Labels: 기능 개선, 라즈베리파이

#7 [rasp/gTTS] gTTS를 이용하는 Gspeak 클래스 및 기능 추가
  hardware/raspberry/module/Env.py
  hardware/raspberry/module/Http.py
  hardware/raspberry/module/Serial.py
  hardware/raspberry/module/Speak.py
  hardware/raspberry/raspberry.py
  hardware/raspberry/testing-files/request_gTTS.py
  hardware/raspberry/testing-files/tts.py
Labels: 기능 추가, 라즈베리파이

#9 [rasp/gTTS/updateSoundMessages] 모바일에서 음료수 변경시 새 사운드파일을 저장하도록 기능 추가
  hardware/raspberry/module/Speak.py
  hardware/raspberry/raspberry.py
Labels: 기능 추가, 라즈베리파이

#10 [docs] Hango 기여 지침서 초안 발행
  CONTRIBUTING.md
Labels: 문서화

#11 [Arduino/hard] 자판기 버튼 교체 - Cap sensor
  hardware/arduino-cap/arduino-cap.ino
  hardware/arduino-ultra/arduino-ultra.ino
Labels: 기능 개선, 기능 추가, 아두이노

#18 [rasp/refectoring] 라즈베리파이 최적화 및 오류 수정
  .gitignore
  hardware/arduino-cap/arduino-cap.ino
  hardware/arduino-ultra/arduino-ultra.ino
  hardware/raspberry/main.py
  hardware/raspberry/module/API.py
  hardware/raspberry/module/DataManager.py
  hardware/raspberry/module/Env.py
  hardware/raspberry/module/Http.py
  hardware/raspberry/module/Serial.py
  hardware/raspberry/module/Speak.py
  hardware/raspberry/module/config.py
  hardware/raspberry/sounds/basic/basic.mp3
  hardware/raspberry/sounds/position/갈아만든 배.mp3
  hardware/raspberry/sounds/position/데자와.mp3
  hardware/raspberry/sounds/position/박카스.mp3
  hardware/raspberry/sounds/position/비타 500.mp3
  hardware/raspberry/sounds/position/스프라이트.mp3
  hardware/raspberry/sounds/position/초록 매실.mp3
  hardware/raspberry/sounds/position/파워에이드.mp3
  hardware/raspberry/sounds/position/펩시 콜라.mp3
  hardware/raspberry/sounds/sold/갈아만든 배.mp3
  hardware/raspberry/sounds/sold/데자와.mp3
  hardware/raspberry/sounds/sold/박카스.mp3
  hardware/raspberry/sounds/sold/비타 500.mp3
  hardware/raspberry/sounds/sold/스프라이트.mp3
  hardware/raspberry/sounds/sold/초록 매실.mp3
  hardware/raspberry/sounds/sold/파워에이드.mp3
  hardware/raspberry/sounds/sold/펩시 콜라.mp3
  hardware/raspberry/sounds/sold_out/갈아만든 배.mp3
  hardware/raspberry/sounds/sold_out/데자와.mp3
  hardware/raspberry/sounds/sold_out/박카스.mp3
  hardware/raspberry/sounds/sold_out/비타 500.mp3
  hardware/raspberry/sounds/sold_out/스프라이트.mp3
  hardware/raspberry/sounds/sold_out/초록 매실.mp3
  hardware/raspberry/sounds/sold_out/파워에이드.mp3
  hardware/raspberry/sounds/sold_out/펩시 콜라.mp3
  hardware/raspberry/testing-files/request_gTTS.py
  hardware/raspberry/testing-files/tts.py
  hardware/solded/solded.cpp
  hardware/solded/solded.h
Labels: 기능 개선, 라즈베리파이

#19 [rasp/omxplayer] 멀티 프로세싱을 이용하여 음악 재생 프로세스를 omxplayer로 변경
  hardware/raspberry/main.py
  hardware/raspberry/module/Speak.py
  hardware/raspberry/module/config.py
Labels: 기능 추가, 라즈베리파이

#23 [arduino/button]아두이노 음료수판매 초음파 -> 스위치 버튼 변경
  hardware/arduino-button/arduino-button.ino
Labels: 기능 개선, 아두이노

#24 [rasp/refectoring] Hango 모듈 최적화
  hardware/raspberry/main.py
  hardware/raspberry/module/API.py
  hardware/raspberry/module/DataManager.py
  hardware/raspberry/module/Http.py
  hardware/raspberry/module/Speak.py
  hardware/raspberry/module/config.py
Labels: 기능 개선, 라즈베리파이

#26 [docs] python 템플릿 적용
  .gitignore
Labels: 문서화

#28 [v1.1.0] Hango RPi v1.1.0 개발 완료
  .gitignore
  CONTRIBUTING.md
  hardware/arduino/README.md
  hardware/arduino/arduino.ino
  hardware/raspberry/raspberry.py
  raspberry/README.md
  raspberry/main.py
  raspberry/module/API.py
  raspberry/module/DataManager.py
  raspberry/module/Http.py
  raspberry/module/Serial.py
  raspberry/module/Speak.py
  raspberry/module/config.py
  raspberry/sounds/basic/basic.mp3
  raspberry/sounds/position/갈아만든 배.mp3
  raspberry/sounds/position/데자와.mp3
  raspberry/sounds/position/박카스.mp3
  raspberry/sounds/position/비타 500.mp3
  raspberry/sounds/position/스프라이트.mp3
  raspberry/sounds/position/초록 매실.mp3
  raspberry/sounds/position/파워에이드.mp3
  raspberry/sounds/position/펩시 콜라.mp3
  raspberry/sounds/sold/갈아만든 배.mp3
  raspberry/sounds/sold/데자와.mp3
  raspberry/sounds/sold/박카스.mp3
  raspberry/sounds/sold/비타 500.mp3
  raspberry/sounds/sold/스프라이트.mp3
  raspberry/sounds/sold/초록 매실.mp3
  raspberry/sounds/sold/파워에이드.mp3
  raspberry/sounds/sold/펩시 콜라.mp3
  raspberry/sounds/sold_out/갈아만든 배.mp3
  raspberry/sounds/sold_out/데자와.mp3
  raspberry/sounds/sold_out/박카스.mp3
  raspberry/sounds/sold_out/비타 500.mp3
  raspberry/sounds/sold_out/스프라이트.mp3
  raspberry/sounds/sold_out/초록 매실.mp3
  raspberry/sounds/sold_out/파워에이드.mp3
  raspberry/sounds/sold_out/펩시 콜라.mp3
Labels: 기능 추가, 라즈베리파이

#30 [rasp/v1.1.0/requirements.txt] RPi 파이썬 패키지 관리를 위한 파일 생성
  requirements.txt
Labels: 라즈베리파이, 문서화, 배포

#31 [v1.1.0/requirements.txt] RPi 파이썬 패키지 관리를 위한 파일 생성
  requirements.txt
Labels: 라즈베리파이, 문서화, 배포

#33 [docs] v1.1.0 리드미 발행
  README.md
Labels: 라즈베리파이, 문서화, 배포

#41 [rasp/v1.2.1] 라즈베리 각종 오류 해결 #40
  README.md
  raspberry/main.py
  raspberry/module/Http.py
  raspberry/module/Serial.py
  raspberry/module/Speak.py
  raspberry/module/config.py
Labels: 기능 개선, 디버깅, 라즈베리파이

#42 [v1.2.1] Hango RPi v1.2.1 배포
  raspberry/main.py
  raspberry/module/Http.py
  raspberry/module/Speak.py
Labels: 기능 개선, 디버깅, 라즈베리파이

#45 [debug] v1.2.1 오류 해결
  LICENSE
  README.md
  raspberry/main.py
  raspberry/module/DataManager.py
  raspberry/module/Http.py
  raspberry/sounds/basic/README.md
  raspberry/sounds/basic/basic.mp3
  raspberry/sounds/duplicate/README.md
  raspberry/sounds/position/README.md
  raspberry/sounds/position/갈아만든 배.mp3
  raspberry/sounds/position/데자와.mp3
  raspberry/sounds/position/박카스.mp3
  raspberry/sounds/position/비타 500.mp3
  raspberry/sounds/position/스프라이트.mp3
  raspberry/sounds/position/초록 매실.mp3
  raspberry/sounds/position/파워에이드.mp3
  raspberry/sounds/position/펩시 콜라.mp3
  raspberry/sounds/sold/README.md
  raspberry/sounds/sold/갈아만든 배.mp3
  raspberry/sounds/sold/데자와.mp3
  raspberry/sounds/sold/박카스.mp3
  raspberry/sounds/sold/비타 500.mp3
  raspberry/sounds/sold/스프라이트.mp3
  raspberry/sounds/sold/초록 매실.mp3
  raspberry/sounds/sold/파워에이드.mp3
  raspberry/sounds/sold/펩시 콜라.mp3
  raspberry/sounds/sold_out/README.md
  raspberry/sounds/sold_out/갈아만든 배.mp3
  raspberry/sounds/sold_out/데자와.mp3
  raspberry/sounds/sold_out/박카스.mp3
  raspberry/sounds/sold_out/비타 500.mp3
  raspberry/sounds/sold_out/스프라이트.mp3
  raspberry/sounds/sold_out/초록 매실.mp3
  raspberry/sounds/sold_out/파워에이드.mp3
  raspberry/sounds/sold_out/펩시 콜라.mp3
Labels: 디버깅, 라즈베리파이

#47 [v1.2.2] 디버깅 완료 후 배포 #44
  raspberry/module/API.py
  raspberry/module/DataManager.py
  raspberry/module/Http.py
  raspberry/sounds/basic/README.md
  raspberry/sounds/basic/basic.mp3
  raspberry/sounds/duplicate/README.md
  raspberry/sounds/position/README.md
  raspberry/sounds/position/갈아만든 배.mp3
  raspberry/sounds/position/데자와.mp3
  raspberry/sounds/position/박카스.mp3
  raspberry/sounds/position/비타 500.mp3
  raspberry/sounds/position/스프라이트.mp3
  raspberry/sounds/position/초록 매실.mp3
  raspberry/sounds/position/파워에이드.mp3
  raspberry/sounds/position/펩시 콜라.mp3
  raspberry/sounds/sold/README.md
  raspberry/sounds/sold/갈아만든 배.mp3
  raspberry/sounds/sold/데자와.mp3
  raspberry/sounds/sold/박카스.mp3
  raspberry/sounds/sold/비타 500.mp3
  raspberry/sounds/sold/스프라이트.mp3
  raspberry/sounds/sold/초록 매실.mp3
  raspberry/sounds/sold/파워에이드.mp3
  raspberry/sounds/sold/펩시 콜라.mp3
  raspberry/sounds/sold_out/README.md
  raspberry/sounds/sold_out/갈아만든 배.mp3
  raspberry/sounds/sold_out/데자와.mp3
  raspberry/sounds/sold_out/박카스.mp3
  raspberry/sounds/sold_out/비타 500.mp3
  raspberry/sounds/sold_out/스프라이트.mp3
  raspberry/sounds/sold_out/초록 매실.mp3
  raspberry/sounds/sold_out/파워에이드.mp3
  raspberry/sounds/sold_out/펩시 콜라.mp3
Labels: 디버깅, 라즈베리파이

#49 [v1.3.0] 가격 변경시 음성 파일 새로 만들도록 기능 추가, 그 외 잔 오류 해결
  raspberry/module/DataManager.py
  raspberry/module/Speak.py
Labels: 기능 개선, 기능 추가, 디버깅, 라즈베리파이, 배포
